=== a2isoftech/emr-apps/packages/emr_one_forms_engine/test/resources/template.schema.json
{
    "$schema": "http://json-schema.org/schema",
    "$id": "https://forms-api.emrgroup.com/template.schema.json",
    "title": "Forms Template",
    "description": "A template form rendered by the Forms engine",
    "type": "object",
    "properties": {
        "title": {
            "description": "The title of the form",
            "type": "string"
        },
        "components": {
            "description": "The form components",
            "type": "array",   
            "items": {
                "type": "object",
                "properties": {
                    "id": {
                        "description": "A unique reference for the component",
                        "type": "string"
                    },
                    "type": {
                        "description": "The type name of the component",
                        "type": "string",
                        "enum": [ "TextInput", "Label", "DatePicker", "YesNoQuestion", "SingleChoice", "MultiChoice" ]
                    },
                    "isRequired": {
                        "type": "boolean",
                        "description": "If completion of this component is required"
                    },
                    "title": {
                        "description": "The title label for the component",
                        "type": "string"
                    },
                    "titleProvider": {
                        "description": "A provider for the title",
                        "$ref": "#/properties/components/items/definitions/dataprovider"
                    },
                    "defaultValue": {
                        "description": "A constant default value for the component",
                        "type": "string"
                    },
                    "defaultValueProvider": {
                        "description": "A provider for the default value",
                        "$ref": "#/properties/components/items/definitions/dataprovider"
                    }
                },
                "allOf": [
                    {
                        "if": {
                            "properties": {
                                "type": { "const": "TextInput" }
                            }
                        },
                        "then": {
                            "properties": {
                                "placeholder": {
                                    "type": "string",
                                    "description": "Placeholder text for the input"
                                },
                                "placeholderProvider": {
                                    "description": "Provider for the placeholder text",
                                    "$ref": "#/properties/components/items/definitions/dataprovider"
                                },
                                "isMultiline": {
                                    "type": "boolean",
                                    "description": "True to allow for multiple lines of text input"
                                },
                                "validators": {
                                    "type": "array",
                                    "description": "A list of validators to validate the user input",
                                    "items": {
                                        "type": "object",
                                        "properties": {
                                            "message": {
                                                "type": "string",
                                                "description": "Custom message displayed when validation fails, overrides any default messages"
                                            },
                                            "messageProvider": {
                                                "description": "A provider for the custom message, overrides any default messages",
                                                "$ref": "#/properties/components/items/definitions/dataprovider"
                                            },
                                            "type": {
                                                "description": "The validator type to use",
                                                "enum": ["Email","Phone","Number","RegEx","NumberRange","Name"]
                                            }                                      
                                        },
                                        "allOf": [
                                            {
                                                "if": {
                                                    "properties": { 
                                                        "type": { "const": "RegEx" }
                                                    }
                                                },
                                                "then": {
                                                    "properties": {
                                                        "matches": {
                                                            "type": "string",
                                                            "description": "Matching this passes validation"
                                                        },
                                                        "notMatches": {
                                                            "type": "string",
                                                            "description": "Matching this fails validation"
                                                        }
                                                    },
                                                    "oneOf":[
                                                        {
                                                            "required": ["matches"]
                                                        },
                                                        {
                                                            "required": ["notMatches"]
                                                        }
                                                    ]
                                                }
                                            },
                                            {
                                                "if": {
                                                    "properties": { 
                                                        "type": { "const": "NumberRange" }
                                                    }
                                                },
                                                "then": {
                                                    "properties": {
                                                        "minValue": {
                                                            "type": "number",
                                                            "description": "The minimum allowable number"
                                                        },
                                                        "maxValue": {
                                                            "type": "number",
                                                            "description": "The maximum allowable number"
                                                        }
                                                    },
                                                    "oneOf":[
                                                        {
                                                            "required": ["minValue"]
                                                        },
                                                        {
                                                            "required": ["maxValue"]
                                                        }
                                                    ]
                                                }
                                            }
                                        ]
                                    }
                                }
                            }
                        }
                    },
                    {
                        "if": {
                            "properties": { 
                                "type": { "const": "Label" }
                            }
                        },
                        "then": {
                            "properties": {
                                "isHTML": {
                                    "type": "boolean",
                                    "description": "true if the label title should be rendered as HTML"
                                }
                            }
                        }
                    },
                    {
                        "if": {
                            "properties": {
                                "type": { "const": "YesNoQuestion" }
                            }
                        },
                        "then": {
                            "properties": {
                                "canCaptureImages": { 
                                    "type": "boolean",
                                    "description": "true if the question can capture images. Defaults to true"
                                },
                                "canCaptureNotes": {
                                    "type": "boolean",
                                    "description": "true if the question can capture notes. Defaults to true"
                                }
                            }
                        }
                    }
                ],
                "required": ["id","type"],
                "definitions": {
                    "dataprovider": {
                        "type": "object",
                        "properties": {
                            "id": {
                                "type": "string",
                                "description": "The id of a defined data provider"
                            },
                            "dataValueId": {
                                "type": "string",
                                "description": "The id of a specific data value"
                            },
                            "parameters": {
                                "type": "object",
                                    "description": "A dictionary of key/values. Use {{component-id}} to use the value from a component in the same section"
                            }
                        } 
                    }
                }
            }
        },
        "layout": {
            "description": "The grouped container and ordering of components",
            "type": "array",
            "items": {
                "type": "object",
                "properties": {
                    "id": {
                        "description": "A unique reference for the section",
                        "type": "string"
                    },
                    "header": {
                        "description": "The displayed header of the section",
                        "type": "string"
                    },
                    "headerProvider": {
                        "description": "A provider for the header",
                        "$ref": "#/properties/components/items/definitions/dataprovider"
                    },
                    "fontColor": {
                        "description": "Hex or named color for the title font",
                        "type": "string"
                    },
                    "backgroundColor": {
                        "description": "Hex or named color for the title background",
                        "type": "string"
                    },
                    "components": {
                        "description": "The sequenced components to display in this section",
                        "type": "array",
                        "items": {
                            "type": "string",
                            "description": "The id of a component"
                        }
                    }
                },
                "required": ["id","components"]
            }
        },
        "dataProviders": {
            "description": "The data providers for the template components",
            "type": "array",
            "items": {
                "type": "object",
                "properties": {
                    "id": {
                        "description": "A unique reference for the data provider",
                        "type": "string"
                    },
                    "type": {
                        "description": "The type of data provider",
                        "type": "string",
                        "enum": [ "Values", "APIRequest", "Boolean", "GraphQLQuery" ]
                    }
                },
                "allOf": [
                    {
                        "if": {
                            "properties": {
                                "type": { "const": "APIRequest" }
                            }
                        },
                        "then": {
                            "properties": {
                                "url": {
                                    "description": "The url to the API method",
                                    "type": "string"
                                },
                                "resultType": {
                                    "description": "The object type returned from the api",
                                    "type": "string",
                                    "enum": ["array","object"]
                                },
                                "resultKey": {
                                    "description": "Property in the result object used as the key / identifier",
                                    "type": "string"
                                },
                                "resultText": {
                                    "description": "Property in the result object used to display text",
                                    "type": "string"
                                },
                                "errorMessage": {
                                    "description": "Message displayed if API request fails",
                                    "type": "string"
                                },
                                "defaultParameters": {
                                    "description": "Default parameters used for a request",
                                    "type": "object",
                                    "patternProperties": {
                                        ".*": { "type": "string" }
                                    }
                                }
                            },
                            "required": ["url"]
                        }
                    },
                    {
                        "if": {
                            "properties": {
                                "type": { "const": "Values" }
                            }
                        },
                        "then": {
                            "properties": {
                                "values": {
                                    "description": "The list of values for the provider",
                                    "type": "array",
                                    "items": {
                                        "type": "object",
                                        "properties": {
                                            "id": {
                                                "description": "A unique reference for the provided data value",
                                                "type": "string"
                                            },
                                            "value": {
                                                "description": "A text value for this data value for subscribed components",
                                                "type": "string"
                                            },
                                            "properties": {
                                                "description": "Custom values included with this data",
                                                "type": "object"
                                            }
                                        }
                                    }
                                }
                            },
                            "required": ["values"]
                        }
                    }
                ],
                "required": ["id","type"]
            }
        },
        "metadata": {
            "type": "object",
            "description": "Object containing metadata keys for the template form"
        }
    },
    "required": ["title","components","layout"]
}

=== a2isoftech/emr-apps/packages/emr_one_forms_engine/test/resources/example.template.json
{
    "$schema": "./template.schema.json",
    "title": "This is an example form",
    "components": [
        {
            "id": "first-name",
            "type": "TextInput",
            "title": "Enter your given name",
            "defaultValueProvider": {
                "id": "text-provider",
                "dataValueId": "value-1"
            },
            "placeholderProvider": {
                "id": "text-provider",
                "dataValueId": "value-2"
            },
            "validators": [
                {
                    "type": "Name"
                }
            ]
        },
        {
            "id": "last-name",
            "type": "TextInput",
            "title": "Enter your surname",
            "defaultValueProvider": {
                "id": "text-provider",
                "dataValueId": "value-3"
            },
            "placeholderProvider": {
                "id": "text-provider",
                "dataValueId": "value-2"
            },
            "validators": [
                {
                    "type": "Name"
                }
            ]
        },
        {
            "id": "yes-question",
            "type": "YesNoQuestion",
            "title": "Answer yes to this one?"
        },
        {
            "id": "no-question",
            "type": "YesNoQuestion",
            "title": "Answer no to this one?"
        },
        {
            "id": "na-question",
            "type": "YesNoQuestion",
            "title": "Answer N/A to this one?",
            "isRequired": false
        }
    ],
    "layout": [
        {
            "id": "top-section",
            "fontColor": "black",
            "backgroundColor": "white",
            "header": "Personal info",
            "components": [ "first-name", "last-name", "yes-question", "no-question", "na-question" ]
        }
    ],
    "dataProviders": [
        {
            "id": "text-provider",
            "type": "Values",
            "values": [
                {
                    "id": "value-1",
                    "value": "John"
                },
                {
                    "id": "value-2",
                    "value": "Name"
                },
                {
                    "id": "value-3",
                    "value": "Doe"
                }
            ]
        },
        {
            "id": "api-provider",
            "type": "APIRequest",
            "url": "mock/endpoint",
            "resultType": "array"
        },
        {
            "id": "graphql-provider",
            "type": "GraphQLQuery",
            "url": "mock/graphql",
            "query": "some query",
            "objectName": "list",
            "idKey": "id",
            "valueKey": "name"
        }
    ]
}
